#!/bin/bash
title=doas
description="- better sudo alternative (aliased to sudo)"
status=on

main() {
        install doas 
        echo "permit nopass root as $USERNAME
permit nopass $USERNAME as root" >> /etc/doas.conf
        chown -c root:root /etc/doas.conf
        chmod -c 0400 /etc/doas.conf
        remove sudo
        ln -s $(which doas) /usr/bin/sudo
        complete -cf doas

        SUPER="doas"
}
