#!/bin/bash
title=pacman
description="- Optimized pacman settings"
status=on

main() {

	sed -i 's/^#ParallelDownloads.*/ParallelDownloads = 20/' /etc/pacman.conf
	sed -i 's/^#Color/Color/' /etc/pacman.conf
	sed -i '/Color/aILoveCandy' /etc/pacman.conf	
	sed -i 's/#VerbosePkgLists/VerbosePkgLists/' /etc/pacman.conf
}
