#!/bin/bash
title=pipewire
description="- Pipewire sound system"
status=on

main() {

	install pipewire wireplumber pipewire-alsa pipewire-jack pipewire-pulse 

	SCRIPT_DIR="/usr/local/bin/"
	SCRIPT_SOUND="$SCRIPT_DIR/pipewire-launcher"
	
	mkdir -p $SCRIPT_DIR

	chown "$USERNAME" "$SCRIPT_DIR"
	touch "$SCRIPT_SOUND"
	
	sudo -u "$USERNAME" sudo chmod +x "$SCRIPT_SOUND"

	echo "#!/bin/sh
pipewire &
pipewire-pulse &
wireplumber &" > "$SCRIPT_SOUND"

}
